from django.urls import path
from . import views

urlpatterns = [
    path("", views.MainView.as_view()),
    path("<str:name>/home/", views.HomeView.as_view()),
    path("<str:name>/faculty/", views.FacultyView.as_view()),
    path("<str:name>/beprogram/", views.BeprogramView.as_view()),
    path("<str:name>/meprogram/", views.MeprogramView.as_view()),
    path("<str:name>/lab/", views.LabView.as_view()),
    path("<str:name>/placement/", views.PlacementView.as_view()),
    path("<str:name>/events/", views.EventsView.as_view()),
    path("<str:name>/club/", views.ClubView.as_view()),
    path("<str:name>/gallery/", views.GalleryView.as_view()),
    path("<str:name>/hod/", views.HodView.as_view()),
    path("<str:name>/mous/", views.Mous1View.as_view()),
    path("<str:name>/publications/", views.PublicationView.as_view()),
    path("<str:name>/proposals/", views.ProposalsView.as_view()),
    path("<str:name>/patents/", views.PatentsView.as_view()),
    path("<str:name>/ds/", views.DisaluminiView.as_view()),
    path("<str:name>/phd/", views.PhddetailsView.as_view()),
    path("<str:name>/hs/", views.HigherstudiesView.as_view()),
     path("<str:name>/ps/", views.ProjectsponceredView.as_view()),
    path("<str:name>/library/", views.DlibraryView.as_view()),
    path("<str:name>/achievements/", views.AchievementView.as_view()),
    path("<str:name>/supportingfaculties/",
         views.SupportingFacultyView.as_view()),
    path("events/<int:pk>/", views.EventsDetailView.as_view()),
    path("result/", views.ResultsView.as_view()),
    path("timetable/", views.TimeTableView.as_view()),
    path("calender/", views.CalenderView.as_view()),
    path("principal/", views.PrincipalView.as_view()),
    path("admission/", views.AdmissionView.as_view()),
    path('facilities/', views.FacilitesView.as_view()),
    path('library/', views.LibraryView.as_view()),
    path('cgallery/', views.CollegeGalleryView.as_view()),
    path('form/', views.FormView.as_view()),
    path('nav/', views.NirfView.as_view()),
    path('foot/', views.FooterView.as_view()),
    path("<str:name>/association/", views.AssociationView.as_view())
    # path("coe/",views.HomeView.as_view()),
    # path("management/",views.HomeView.as_view()),
    # path("feedback/",views.HomeView.as_view()),
]
